[package]
name = "neuronav"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "neuronav"
crate-type = ["cdylib", "rlib"]

[dependencies]

actix-web = "4.3.1"

# Interfacing with Python
pyo3 = { version = "0.18.3", features = ["extension-module"], optional = true }
numpy = { version = "0.18", optional = true }

# SIGINT handling
ctrlc = { version = "3.2.5", optional = true }

[features]
python = ["dep:pyo3", "dep:numpy", "dep:ctrlc"]
