# class Database:
#    @staticmethod
#    def initialize(path: str) -> None: ...
#
#    @staticmethod
#    def open(path: str) -> None: ...
#
#    def add_model(self, model_metadata: ModelMetadata) -> None: ...

class DataType:
    @staticmethod
    def json() -> DataType: ...
