# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.dockerfile
      target: backend-prod
    volumes:
      - ../${DB_PATH?database path}:/data.db
    ports:
      - 8080:8080
  frontend:
    build:
     context: ..
     dockerfile: docker/frontend.dockerfile
     target: frontend-prod
    ports:
      - 3000:3000
    environment:
      - BACKEND_ORIGIN=http://backend
      - BACKEND_PORT=8080

networks:
  app-network:
    driver: bridge
